# Generated by Django 5.2.7 on 2025-11-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMDeustoB', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Actor', 'verbose_name_plural': 'Actores'},
        ),
    ]
