# Generated by Django 5.2.7 on 2025-11-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDeustoB', '0002_alter_actor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='sinopsis',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
