# Generated by Django 5.2.7 on 2025-11-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDeustoB', '0003_alter_pelicula_sinopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='peliculas',
            field=models.ManyToManyField(blank=True, null=True, related_name='actores', to='IMDeustoB.pelicula'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='generos',
            field=models.ManyToManyField(blank=True, null=True, related_name='peliculas', to='IMDeustoB.genero'),
        ),
    ]
