# Generated by Django 5.2.7 on 2025-11-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDeustoB', '0004_actor_peliculas_alter_pelicula_generos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='peliculas',
            field=models.ManyToManyField(blank=True, related_name='actores', to='IMDeustoB.pelicula'),
        ),
    ]
