# Generated by Django 5.2.7 on 2025-11-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDeustoB', '0005_alter_actor_peliculas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='peliculas',
            field=models.ManyToManyField(blank=True, null=True, related_name='actores', to='IMDeustoB.pelicula'),
        ),
    ]
